name: Deploy XAMPP

on:
  push:
    branches:
      - "*"

env:
  XAMPP_VERSION: 8.1.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download XAMPP
      run: |
        sudo apt update
        sudo apt upgrade -y
        wget https://www.apachefriends.org/xampp-files/${XAMPP_VERSION}/xampp-linux-x64-${XAMPP_VERSION}-2-installer.run
        chmod +x xampp-linux-${XAMPP_VERSION}-0-installer.run
        sudo ./xampp-linux-${XAMPP_VERSION}-0-installer.run
    - name: Start XAMPP
      run: |
        sudo /opt/lampp/lampp start
        sudo /opt/lampp/lampp startapache
        sudo /opt/lampp/lampp startmysql
